# https://taskfile.dev

version: "3"

tasks:
  default:
    desc: Runs all of the default tasks
    cmds:
      - task: lint
      - task: test

  test:
    desc: Run the tests
    cmds:
      - go test -race -vet=off -p 1 -covermode=atomic -coverprofile=coverage.out ./...

  lint:
    desc: Lint the code using golangci
    cmds:
      - golangci-lint run --timeout 5m0s

  fmt:
    desc: gofumpt all code
    cmds:
      - gofumpt -w -l .

  examples:
    desc: Build all examples
    dir: examples
    cmds:
      - go build -v ./...
